### ISSUE TITLE
`is_cyclic` for undirected graphs

### ISSUE THREAD

**Issue by samwycherley** [JuliaGraphs/Graphs.jl#34] opened 2021-11-02 10:34 UTC
Issue previously open at [#1518](https://github.com/sbromberger/LightGraphs.jl/issues/1518) for LightGraphs.jl.

The `is_cyclic` function in LightGraphs.jl works well for directed graphs but for undirected graphs returns `true` for any nonempty graph. The usual definition for undirected graphs is that cycles don't contain repeated links, so 1->2->1 is not considered a cycle (absent multiple edges.)

Useful for me because I want a function that will test whether an (undirected) network is a tree and easiest way to check that is to confirm the graph is acyclic+connected

**Comment by jpfairbanks** [comment] 2021-11-08 18:16
@samwycherley, Are you interested in finding an algorithm for this? If not I'll close since @mtfishman solved your direct problem. The non-backtracking part makes its a bit harder.

**Comment by samwycherley** [comment] 2021-11-08 19:35
When I have time, I'll try and work on it and put up a PR. Feel free to close in the meantime.

**Comment by pgrepds** [comment] 2022-01-19 16:35
Is someone working on this Issue? If not, I would like to implement it as a first issue. If we want to add a generic function `is_tree` as suggested, we might need to consider  the disconnected case as well (a graph could have multiple trees as components -> forest).

**Comment by gdalle** [comment] 2022-03-10 07:53
@pgrepds feel free to contribute, it is a nice first issue to tackle!

**Comment by etiennedeg** [comment] 2022-08-29 14:13
[Because of this](https://github.com/sbromberger/LightGraphs.jl/issues/1518#issuecomment-768563457) that say the behavior was intended, wouldn't it be a breaking change ? To clear the confusion, maybe we could deprecate this function , and have a `is_directed_acyclic` that would work only for directed graphs, and a `is_forest` that would work only for undirected graphs ?

**Comment by natema** [comment] 2022-09-20 09:58
It seems that #168 is ready to be merged to close this. 
The pull request is by a student in [our team at INRIA UCA](https://team.inria.fr/coati/) and we hope to contribute more now that more members of the team are starting to use Julia.

**Comment by etiennedeg** [comment] 2022-09-21 14:52
closed by #168

**Closed by etiennedeg** 2022-09-21 14:52 UTC
Labels: bug, good first issue
